import React from 'react';
import Typography from "@material-ui/core/Typography";
import { Card, CardHeader, CardContent } from '@material-ui/core';
import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
    root: {
        width: "100%",
        height: "100%",
        background: "#354051",
    },
    heading: {
      color: "white",
      textAlign: "center",
      marginBottom: "1rem",
    },
    timeline: {
        position: "relative",
        left: "50%",
        transform: "translateX(-50%)",
        maxWidth: '800px',
        padding: "40px 20px 20px 20px",
    },
    timelineEntry: {
        marginTop: '10px',
        '&:lastOfType': {
            marginBottom: '0px',
        },
        display: 'block',
    },
    timelineEntryChip: {
        float: 'left',
        marginRight: '5px',
        marginBottom: '5px',
        display: 'inline-block',
    },
    timelineEntries: {
        display: 'inline-block',
        marginTop: '20px',
    },
}));


const Privacy = () => {

  const classes = useStyles();

  return (
    <div className={classes.root}>
            <div className={classes.timeline}>
                <div className={classes.timelineEntry}>
                    <Typography variant="h3" className={classes.heading}>
                      PRIVACY POLICY
                    </Typography>
                    <Card>
                      <CardContent expandable={true}>
                        <p>This policy is effective as of 2022-03-29.</p>
                        <p>Goran Drakulić Portfolio site („we“, „our“ or „us“) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Goran Drakulić.</p>
                        <p>This Privacy Policy applies to our site named Goran Drakulić Portfolio, and its associated subdomains (collectively, our "Service"). By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.</p>
                        <p>Goran Drakulić Portfolio site is an Ad Supported and Free site. Basic Service is provided at no cost and is intended for use as is</p>
                        <p>If you choose to use Service, then you agree to the collection and use of information in relation to this policy. Collected Personal Information is used for providing and improving the Service, and will not be used or shared with anyone except as described in this Privacy Policy</p>
                        <p>The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at Goran Drakulić Portfolio site, unless otherwise defined in this Privacy Policy.</p>
                      </CardContent>
                    </Card>
                    <Card>
                        <CardHeader
                            title="Definitions and key terms"
                            titleTypographyProps={{ variant: 'h6' }}
                        />
                        <CardContent expandable={true}>
                          <p>
                             For this Privacy Policy::
                          <ul>
                            <li><b>Cookie:</b> file with a small amount of data generated by a website and saved by your web browser, that is commonly used as anonymous unique identifier. It is sent to your browser from the websites that you visit and is stored on your device's internal memory. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                            <li><b>Company:</b> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Goran Drakulić Portfolio site that is responsible for your information under this Privacy Policy.</li>
                            <li><b>Country:</b> where Goran Drakulić Portfolio site or the owners/founders of Goran Drakulić Portfolio site are based, in this case is Serbia.</li>
                            <li><b>Customer:</b> refers to the company, organization or person that signs up to use the Goran Drakulić Portfolio Service to manage the relationships with your consumers or service users.</li>
                            <li><b>Device:</b> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Goran Drakulić Portfolio site and use the services.</li>
                            <li><b>IP address:</b> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                            <li><b>Personnel:</b> refers to those individuals who are employed by Goran Drakulić Portfolio site or are under contract to perform a service on behalf of one of the parties.</li>
                            <li><b>Personal Data:</b> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                            <li><b>Service:</b> refers to the service provided by Goran Drakulić Portfolio site as described in the relative terms (if available) and on this platform.</li>
                            <li><b>Third-party service:</b> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                            <li><b>Website:</b> Goran Drakulić Portfolio site, which can be accessed via this URL: https://sites.google.com/view/portfoliogd.</li>
                            <li><b>You:</b> a person or entity that is registered with Goran Drakulić Portfolio site to use the Services.</li>
                          </ul>
                        </p>
                      </CardContent>
                    </Card>
                </div>
            </div>
        </div>
  );
}

export default Privacy;
